# -*- coding: utf-8 -*-
"""LinearSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHqnE-BB2aZM7IDSmkQqG1Eko2MS9hr6
"""

# Searching algorithms - Linear Search

def linearSearch(array, value):
    for i in range(len(array)):
        if array[i] == value:
            return i
    return -1



print(linearSearch([20,40,30,50,90], 90))